### ISSUE TITLE
EEMD.py (pycharm, python 3.5.2, windows 10) errors

### ISSUE THREAD

**Issue by donaldtone** [laszukdawid/PyEMD#1]
C:\ProgramData\Anaconda3\python.exe "D:/AI/workspace/ML study/1-Basic/PyEMD-master/PyEMD/EEMD.py"
Traceback (most recent call last):
  File "D:/AI/workspace/ML study/1-Basic/PyEMD-master/PyEMD/EEMD.py", line 107, in <module>
    IMF, EXT, ITER, imfNo = EEMD().eemd(S, timeLine, maxImf)
  File "D:/AI/workspace/ML study/1-Basic/PyEMD-master/PyEMD/EEMD.py", line 42, in __init__
    self.EMD = EMD()
TypeError: 'module' object is not callable

Process finished with exit code 1

**Comment by laszukdawid** [comment]
Thank you @donaldtone for reporting this. It should be fixed now and I'd really appreciate if you could test it. I'll also update PyPi soon so you'll be able to download from there.
