### ISSUE TITLE
Runtime Error: An attempt has been made to start a new process before the         current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by huangzhaor** [laszukdawid/PyEMD#31]
I use the pycharm to install the package named EMD-signal 0.2.6.
I don't know why this error come up.
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by huangzhaor** [comment]
I am executing the following code：
from EEMD import EEMD
import numpy as np
s = np.random.random(100)
eemd = EEMD()
eIMFs = eemd(s)

**Comment by huangzhaor** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\Anaconda  Python ide\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "G:\Anaconda  Python ide\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "G:\Anaconda  Python ide\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "G:\Anaconda  Python ide\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "G:\Anaconda  Python ide\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "G:\Anaconda  Python ide\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "G:\Anaconda  Python ide\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\EMD\Pyeemd-EEMD.py", line 5, in <module>
    eemd = EEMD()
  File "C:\Users\asus-1\AppData\Roaming\Python\Python36\site-packages\PyEMD\EEMD.py", line 87, in __init__
    self.pool = Pool(processes=processes)
  File "G:\Anaconda  Python ide\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "G:\Anaconda  Python ide\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "G:\Anaconda  Python ide\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "G:\Anaconda  Python ide\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "G:\Anaconda  Python ide\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "G:\Anaconda  Python ide\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "G:\Anaconda  Python ide\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "G:\Anaconda  Python ide\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by laszukdawid** [comment]
This is a problem with Windows and its handling of the subprocesses. As per [stackoverflow](https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing) answer, try surrounding the code with `if __name__ == "__main__"`, something like:

```python
from EEMD import EEMD
import numpy as np

if __name__ == "__main__":
  s = np.random.random(100)
  eemd = EEMD()
  eIMFs = eemd(s)
```

**Comment by huangzhaor** [comment]
Thank you for your help.It works well.
