### ISSUE TITLE
CEEMDAN

### ISSUE THREAD

**Issue by wunderbarr** [laszukdawid/PyEMD#53]
Hello,
When I would like to use CEEMDAN to extract IMFs, I encounter following exceptions.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\mining\anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\mining\anaconda\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\mining\anaconda\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\mining\anaconda\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\mining\anaconda\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\mining\anaconda\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\mining\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\internship\code\sbs.py", line 17, in <module>
    cemd = CEEMDAN()
  File "D:\mining\anaconda\lib\site-packages\PyEMD\CEEMDAN.py", line 115, in __init__
    self.pool = Pool(processes=processes)
  File "D:\mining\anaconda\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "D:\mining\anaconda\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "D:\mining\anaconda\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "D:\mining\anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\mining\anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\mining\anaconda\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\mining\anaconda\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\mining\anaconda\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
 
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
 
            if __name__ == '__main__':
                freeze_support()
                ...
 
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```
And I just wrote simple code:
```
emd = CEEMDAN()
IMFs = emd.ceemdan(np.random.random(100))
```
And in documentation `ceemdan` has not been mentioned, but I read the source code, I viewed this method. I think this is the way for using `CEEMDAN`. 
Is there any solution for that?

**Comment by laszukdawid** [comment]
Hey, apologies for delay. That's a common problem so I might actually add F.A.Q. to readme. It basically says that you need to run code from `__main__` section. It's related to have mutliprocessing is handled on the Windows.

Try something like:
```python
from PyEMD import CEEMDAN

if __name__ == "__main__":
  ceemdan = CEEMDAN()
  s = np.random.random(100)
  ceIMFs = ceemdan(s)  # or ceemdan.ceemdan(s)
```
