### ISSUE TITLE
PyEMD installation version 0.5.1 fails on Linux

### ISSUE THREAD

**Issue by Roymprog** [laszukdawid/PyEMD#69]
In my project there is a dependency on [textacy](https://github.com/chartbeat-labs/textacy), that depends on PyEMD. 

It seems I cannot install this package using pip by running *pip install -r requirements.txt --no-cache-dir*. Pip itself is installed using anaconda, if that's relevant.

The *requirements.txt* looks as follows:

```
textacy==0.7.0 --> depends on pyemd >= 0.3, so tries to get 0.5.1(latest as of now)
pandas==0.21
gensim==3.3.0
xlrd==1.1.0
abbreviations==0.1.5
spacy-langdetect==0.1.2
PyPDF2==1.26.0
matplotlib==3.1.0
wordcloud==1.5.0
scattertext==0.0.2.52
```

I've tried changing the numpy version, as I thought it might have to do with numpy version compatibility. Using the latest version(1.18.1) of numpy does fix this.

<details>
<summary>Click to see error</summary>

```
Collecting pyemd>=0.3.0 (from textacy==0.7.0->-r requirements.txt (line 1))
  Downloading ***/api/pypi/releases_pypi_all/packages/packages/c0/c5/7fea8e7a71cd026b30ed3c40e4c5ea13a173e28f8855da17e25271e8f545/pyemd-0.5.1.tar.gz (91kB)
    100% |████████████████████████████████| 92kB 5.0MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pyemd.egg-info
    writing pip-egg-info/pyemd.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/pyemd.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/pyemd.egg-info/requires.txt
    writing top-level names to pip-egg-info/pyemd.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/pyemd.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dr1_6j7o/pyemd/setup.py", line 121, in <module>
        'Programming Language :: Python :: 3.6',
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/home/user/Applications/anaconda3/envs/py36_txt2insights/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/user/Applications/anaconda3/envs/py36_txt2insights/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/user/Applications/anaconda3/envs/py36_txt2insights/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/home/user/Applications/anaconda3/envs/py36_txt2insights/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/home/user/Applications/anaconda3/envs/py36_txt2insights/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-dr1_6j7o/pyemd/setup.py", line 78, in finalize_options
        self.include_dirs.append(numpy.get_include())
    AttributeError: module 'numpy' has no attribute 'get_include'

```
</details>

**Comment by Roymprog** [comment]
Oops, issue added to the wrong PyEMD project.
